version: "2"
services:

  elasticsearch:
    image: elasticsearch:5.0
    volumes: 
      - elasticsearchData:/usr/share/elasticsearch/data
    expose:
      - 9200
  
  logstash:
    image: logstash:5.0
    expose:
      - 25826
      - 25826/udp
    volumes:
      - ./conf:/conf
    links:
      - elasticsearch:db
    command: logstash -f /conf/syslog.conf
  
  kibana:
    image: kibana:5.0
    links:
      - elasticsearch:elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601
  
volumes:
  elasticsearchData:
    driver: local
